# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigurationService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConfigurationService.proto',
  package='acidaes.datanext.configuration',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x43onfigurationService.proto\x12\x1e\x61\x63idaes.datanext.configuration\"\x12\n\x10GetModelsRequest\"0\n\nModelEntry\x12\x0f\n\x07ModelId\x18\x01 \x01(\t\x12\x11\n\tModelName\x18\x02 \x01(\t\"3\n\x0fGetModelRequest\x12\x0f\n\x07OwnerId\x18\x01 \x01(\x05\x12\x0f\n\x07ModelId\x18\x02 \x01(\t\"D\n\rGetModelReply\x12\x0f\n\x07OwnerId\x18\x01 \x01(\x05\x12\x0f\n\x07ModelId\x18\x02 \x01(\t\x12\x11\n\tModelName\x18\x03 \x01(\t\"L\n\x0eGetModelsReply\x12:\n\x06Models\x18\x01 \x03(\x0b\x32*.acidaes.datanext.configuration.ModelEntry\"9\n\x12GetEntitiesRequest\x12\x0f\n\x07OwnerId\x18\x01 \x01(\x05\x12\x12\n\nEntityName\x18\x02 \x01(\t\"F\n\x05\x46ield\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\r\n\x05Label\x18\x02 \x01(\t\x12\x10\n\x08\x44\x61taType\x18\x03 \x01(\t\x12\x0e\n\x06Length\x18\x04 \x01(\x05\"\xba\x01\n\x0e\x45ntityMetadata\x12\x0f\n\x07OwnerId\x18\x01 \x01(\x05\x12\x10\n\x08ItemType\x18\x02 \x01(\x05\x12\x13\n\x0bPrimaryKeys\x18\x03 \x03(\t\x12\x35\n\x06\x46ields\x18\x04 \x03(\x0b\x32%.acidaes.datanext.configuration.Field\x12\x12\n\nEntityName\x18\x05 \x01(\t\x12\x10\n\x08\x45ntityId\x18\x06 \x01(\x05\x12\x13\n\x0b\x44\x65scription\x18\x07 \x01(\t\"e\n\x10GetEntitiesReply\x12\x0f\n\x07OwnerId\x18\x01 \x01(\x05\x12@\n\x08\x45ntities\x18\x02 \x03(\x0b\x32..acidaes.datanext.configuration.EntityMetadata2\xf5\x02\n\x1c\x44\x61tanextConfigurationService\x12o\n\tGetModels\x12\x30.acidaes.datanext.configuration.GetModelsRequest\x1a..acidaes.datanext.configuration.GetModelsReply\"\x00\x12m\n\x08GetModel\x12/.acidaes.datanext.configuration.GetModelRequest\x1a..acidaes.datanext.configuration.GetModelsReply\"\x00\x12u\n\x0bGetEntities\x12\x32.acidaes.datanext.configuration.GetEntitiesRequest\x1a\x30.acidaes.datanext.configuration.GetEntitiesReply\"\x00\x62\x06proto3')
)




_GETMODELSREQUEST = _descriptor.Descriptor(
  name='GetModelsRequest',
  full_name='acidaes.datanext.configuration.GetModelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=80,
)


_MODELENTRY = _descriptor.Descriptor(
  name='ModelEntry',
  full_name='acidaes.datanext.configuration.ModelEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ModelId', full_name='acidaes.datanext.configuration.ModelEntry.ModelId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ModelName', full_name='acidaes.datanext.configuration.ModelEntry.ModelName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=130,
)


_GETMODELREQUEST = _descriptor.Descriptor(
  name='GetModelRequest',
  full_name='acidaes.datanext.configuration.GetModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnerId', full_name='acidaes.datanext.configuration.GetModelRequest.OwnerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ModelId', full_name='acidaes.datanext.configuration.GetModelRequest.ModelId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=183,
)


_GETMODELREPLY = _descriptor.Descriptor(
  name='GetModelReply',
  full_name='acidaes.datanext.configuration.GetModelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnerId', full_name='acidaes.datanext.configuration.GetModelReply.OwnerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ModelId', full_name='acidaes.datanext.configuration.GetModelReply.ModelId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ModelName', full_name='acidaes.datanext.configuration.GetModelReply.ModelName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=253,
)


_GETMODELSREPLY = _descriptor.Descriptor(
  name='GetModelsReply',
  full_name='acidaes.datanext.configuration.GetModelsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Models', full_name='acidaes.datanext.configuration.GetModelsReply.Models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=331,
)


_GETENTITIESREQUEST = _descriptor.Descriptor(
  name='GetEntitiesRequest',
  full_name='acidaes.datanext.configuration.GetEntitiesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnerId', full_name='acidaes.datanext.configuration.GetEntitiesRequest.OwnerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EntityName', full_name='acidaes.datanext.configuration.GetEntitiesRequest.EntityName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=390,
)


_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='acidaes.datanext.configuration.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='acidaes.datanext.configuration.Field.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Label', full_name='acidaes.datanext.configuration.Field.Label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DataType', full_name='acidaes.datanext.configuration.Field.DataType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Length', full_name='acidaes.datanext.configuration.Field.Length', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=462,
)


_ENTITYMETADATA = _descriptor.Descriptor(
  name='EntityMetadata',
  full_name='acidaes.datanext.configuration.EntityMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnerId', full_name='acidaes.datanext.configuration.EntityMetadata.OwnerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ItemType', full_name='acidaes.datanext.configuration.EntityMetadata.ItemType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PrimaryKeys', full_name='acidaes.datanext.configuration.EntityMetadata.PrimaryKeys', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Fields', full_name='acidaes.datanext.configuration.EntityMetadata.Fields', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EntityName', full_name='acidaes.datanext.configuration.EntityMetadata.EntityName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EntityId', full_name='acidaes.datanext.configuration.EntityMetadata.EntityId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Description', full_name='acidaes.datanext.configuration.EntityMetadata.Description', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=651,
)


_GETENTITIESREPLY = _descriptor.Descriptor(
  name='GetEntitiesReply',
  full_name='acidaes.datanext.configuration.GetEntitiesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnerId', full_name='acidaes.datanext.configuration.GetEntitiesReply.OwnerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Entities', full_name='acidaes.datanext.configuration.GetEntitiesReply.Entities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=754,
)

_GETMODELSREPLY.fields_by_name['Models'].message_type = _MODELENTRY
_ENTITYMETADATA.fields_by_name['Fields'].message_type = _FIELD
_GETENTITIESREPLY.fields_by_name['Entities'].message_type = _ENTITYMETADATA
DESCRIPTOR.message_types_by_name['GetModelsRequest'] = _GETMODELSREQUEST
DESCRIPTOR.message_types_by_name['ModelEntry'] = _MODELENTRY
DESCRIPTOR.message_types_by_name['GetModelRequest'] = _GETMODELREQUEST
DESCRIPTOR.message_types_by_name['GetModelReply'] = _GETMODELREPLY
DESCRIPTOR.message_types_by_name['GetModelsReply'] = _GETMODELSREPLY
DESCRIPTOR.message_types_by_name['GetEntitiesRequest'] = _GETENTITIESREQUEST
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['EntityMetadata'] = _ENTITYMETADATA
DESCRIPTOR.message_types_by_name['GetEntitiesReply'] = _GETENTITIESREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetModelsRequest = _reflection.GeneratedProtocolMessageType('GetModelsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMODELSREQUEST,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.GetModelsRequest)
  ))
_sym_db.RegisterMessage(GetModelsRequest)

ModelEntry = _reflection.GeneratedProtocolMessageType('ModelEntry', (_message.Message,), dict(
  DESCRIPTOR = _MODELENTRY,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.ModelEntry)
  ))
_sym_db.RegisterMessage(ModelEntry)

GetModelRequest = _reflection.GeneratedProtocolMessageType('GetModelRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMODELREQUEST,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.GetModelRequest)
  ))
_sym_db.RegisterMessage(GetModelRequest)

GetModelReply = _reflection.GeneratedProtocolMessageType('GetModelReply', (_message.Message,), dict(
  DESCRIPTOR = _GETMODELREPLY,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.GetModelReply)
  ))
_sym_db.RegisterMessage(GetModelReply)

GetModelsReply = _reflection.GeneratedProtocolMessageType('GetModelsReply', (_message.Message,), dict(
  DESCRIPTOR = _GETMODELSREPLY,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.GetModelsReply)
  ))
_sym_db.RegisterMessage(GetModelsReply)

GetEntitiesRequest = _reflection.GeneratedProtocolMessageType('GetEntitiesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETENTITIESREQUEST,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.GetEntitiesRequest)
  ))
_sym_db.RegisterMessage(GetEntitiesRequest)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), dict(
  DESCRIPTOR = _FIELD,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.Field)
  ))
_sym_db.RegisterMessage(Field)

EntityMetadata = _reflection.GeneratedProtocolMessageType('EntityMetadata', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYMETADATA,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.EntityMetadata)
  ))
_sym_db.RegisterMessage(EntityMetadata)

GetEntitiesReply = _reflection.GeneratedProtocolMessageType('GetEntitiesReply', (_message.Message,), dict(
  DESCRIPTOR = _GETENTITIESREPLY,
  __module__ = 'ConfigurationService_pb2'
  # @@protoc_insertion_point(class_scope:acidaes.datanext.configuration.GetEntitiesReply)
  ))
_sym_db.RegisterMessage(GetEntitiesReply)



_DATANEXTCONFIGURATIONSERVICE = _descriptor.ServiceDescriptor(
  name='DatanextConfigurationService',
  full_name='acidaes.datanext.configuration.DatanextConfigurationService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=757,
  serialized_end=1130,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetModels',
    full_name='acidaes.datanext.configuration.DatanextConfigurationService.GetModels',
    index=0,
    containing_service=None,
    input_type=_GETMODELSREQUEST,
    output_type=_GETMODELSREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetModel',
    full_name='acidaes.datanext.configuration.DatanextConfigurationService.GetModel',
    index=1,
    containing_service=None,
    input_type=_GETMODELREQUEST,
    output_type=_GETMODELSREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEntities',
    full_name='acidaes.datanext.configuration.DatanextConfigurationService.GetEntities',
    index=2,
    containing_service=None,
    input_type=_GETENTITIESREQUEST,
    output_type=_GETENTITIESREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATANEXTCONFIGURATIONSERVICE)

DESCRIPTOR.services_by_name['DatanextConfigurationService'] = _DATANEXTCONFIGURATIONSERVICE

# @@protoc_insertion_point(module_scope)
